### ISSUE TITLE
add validator for arrays

### ISSUE THREAD

**Issue by iffyuva** [codemancers/rails_legit#1]
{open for discussion}

``` ruby
  validates :user_ids, array: true
  validates :user_ids, array: { in: [10, 11, 12, 13] }
  validates :user_ids, array: { in: :fetch_valid_ids_from_db }
  # ....
  private

  def fetch_valid_ids_from_db
    Users.active.pluck(:id)
  end
```

**Comment by iffyuva** [comment]
there should be an option for exclusion of values also. like

``` ruby
  validates :user_ids, array: { not_in: [20, 21, 22] }
```

**Comment by kgrz** [comment]
Should we implement this with a generic comparision? that is, `[1, 3, 5], array: { in: [5, 1, 3] }` should return true right? Then there should be another option to specify if the order is strict or non-strict.

**Comment by iffyuva** [comment]
yes, no need for sequence to match. im not sure about second question, i.e order.
