### ISSUE TITLE
add validator for hashes

### ISSUE THREAD

**Issue by iffyuva** [codemancers/rails_legit#2]
``` ruby
  validates features, hash: true
  validates features, hash: { keys: ['feature1', 'feature2'] }
  validates features, hash: { values: ['value1', 'value2'] }
```

**Comment by iffyuva** [comment]
there should be an option to exclude `keys` and `values`

**Comment by kgrz** [comment]
But doesn't this become an array validator? :)

**Comment by kgrz** [comment]
Ignore Ignore Ignore Ignore.

**Comment by kgrz** [comment]
I'm not really convinced about the UI. This is what I wrote until now:

``` ruby
validates features, hash: { keys_in: [:one, :two, :three] }
validates features, hash: { keys_not_in: [:one, :two, :three] }
validates features, hash: { values_in: [1, 2, 3] }
```

But I was thinking this would be much cleaner:

``` ruby
validates features, hash: { keys: { in: [:one, :two, :three], not_in: [:four, :five] } }
validates features, hash: { values: { in: [1, 2, 3], not_in: [4, 5] } }
validates features, hash: { eq: {one: 1, two: 2, three: 3} }
```

Also, should we treat the keys as ambiguous to being a symbol or string? since Rails convention is to let all DB record attributes work with both string and symbol keys i.e., `:one` == "one".

Not sure if that makes sense.

**Comment by iffyuva** [comment]
for now, lets just go with assumption that keys and values are just arrays for first cut. maybe we can think about these complex scenarios later.

and i agree, keys can be either symbol or string. its good to have this feature.

**Comment by kgrz** [comment]
So, that means we need not check for `:in` and just assume that we check for exact match?

**Comment by iffyuva** [comment]
i think, we should just support `:in`, and not `:not_in`, and `:eq`

**Comment by kgrz** [comment]
okay, can you give an example?  Just like the first one you gave?

**Comment by iffyuva** [comment]
im saying, lets support only these options:

``` ruby
  validates features, hash: true
  validates features, hash: { keys: ['feature1', 'feature2'] }
  validates features, hash: { values: ['value1', 'value2'] }
```

lets not think about `:in`, `:not_in`, and `:eq`. the default behavior should be keys should be one of the values in the array provided.

**Comment by kgrz** [comment]
okay
